In [1]:
import tensorflow as tf

In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World")

Using the with allows us to not close the session manually as it gets done automatically.

In [6]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [7]:
print(result)

b'Hello World'


In [8]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [12]:
result

30

In [13]:
const = tf.constant(10)

In [14]:
fill_mat = tf.fill((4, 4), 10) #Give me a 4x4 matrix filled with 10s

In [15]:
myzeros = tf.zeros((4, 4))

In [16]:
myones = tf.ones((4, 4))

In [17]:
myrand = tf.random_normal((4, 4))

In [18]:
myrandu = tf.random_uniform((4, 4), minval = 0, maxval = 1)

# None of the above things have been run yet, you need a session to run a tensorflow operation

In [19]:
my_ops = [const, fill_mat, myzeros, myones, myrand, myrandu]

In [20]:
with tf.Session() as sess:
    for op in my_ops:
        print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.39684403  2.9371717   0.52636534 -1.13606012]
 [ 1.1566664   0.41775459  0.99324882  0.13657494]
 [-1.48411024 -1.23475993 -1.03343618 -1.12625027]
 [ 0.08692101  0.9585675  -1.169662    0.11149986]]
[[ 0.0149138   0.30460203  0.15176952  0.97039378]
 [ 0.19012117  0.09301424  0.21232927  0.27494812]
 [ 0.26238787  0.67073798  0.16141784  0.00432706]
 [ 0.20177031  0.86959887  0.48228574  0.73444307]]


In [21]:
a = tf.constant([[1, 2], [3, 4]])

In [22]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [23]:
b = tf.constant([[10], [100]])

In [24]:
result = tf.matmul(a, b)

In [26]:
with tf.Session() as sess:
    print(sess.run(result))

[[210]
 [430]]
