Numpy


In [1]:
import numpy as np

In [ ]:
my_list = [1, 2, 3]

Cast a regular array into a numpy array

In [3]:
numpy_array = np.array(my_list)

Create an empty array

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Create an array of zeros

In [12]:
np.zeros((3, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Create an array of ones

In [11]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

Create a linearly spaced array. Specify the number range and then how many points you want 
evenly spaced.

In [14]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

Create random numbers

In [15]:
np.random.randint(0, 10)


8

In [16]:
np.random.randint(0, 100, (3, 3))

array([[49, 53, 84],
       [73, 83, 36],
       [ 4, 83, 87]])

To make sure the random generator always creates the same random numbers, then specify a seed.

In [4]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [5]:
arr.max()


95

In [6]:
arr.min()

9

In [7]:
arr.mean()

60.8

Give the index position of the maximum value

In [ ]:
arr.argmax()

Reshape the array, as long as the dimensions matching in total length.

In [8]:
arr.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [2]:
mat = np.arange(0, 100).reshape(10, 10)

In [4]:
mat[4, 1]

41

In [5]:
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
mat[5, :]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [7]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [8]:
my_filter = mat > 50


In [9]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])